### PR TITLE
feat: Add reverse route

### PR DESCRIPTION
**Pull request by nhcarrigan**
Adds a reverse route to the api. Accepts a body parameter `string`, returns a JSON response containing the `originalString` and `reversedString`.

### CODE REVIEW

**Comment by ZiyanK** [comment]
Logic looks good to me. Kindly resolve merge conflicts and I'll accept it instantly :)

**Comment by nhcarrigan** [comment]
Will do as soon as I'm home 😁

**Comment by nhcarrigan** [comment]
@ZiyanK I have resolved the conflict.

**Comment by ZiyanK** [comment]
There still seems to be some conflicts. Kindly ensure they are resolved @nhcarrigan

**Comment by nhcarrigan** [comment]
Resolved again - I'll keep an eye out for further conflicts. 😁

**Review by ZiyanK — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
