### PR TITLE
Added route for automorphic number

### PR DESCRIPTION
**Pull request by piyushverma001**
Please review it and let me know it there are any issues with it. Or else kindly merge it.
Cheers.

### CODE REVIEW

**Comment by piyushverma001** [comment]
Kindly review this PR and merge it or else let me know the improvements.

**Comment by piyushverma001** [comment]
Someone kindly review this PR and merge it or let me know the changes.!

**Comment by ZiyanK** [comment]
Logic for harshad number isn't present.

**Comment by ZiyanK** [comment]
Issue has been solved :+1:

**Comment by piyushverma001** [comment]
@ZiyanK Sir kindly add `hacktoberfest-accepted` label if you feel this was a genuine attempt at solving a problem.

Thank you.
Cheers.

**Pull request closed without merging**
