### PR TITLE
#8: Add /amicable route as well as tests

### LINKED ISSUE #8: Add a route to check if two numbers are amicable or not
Please describe the feature you want this project to offer
A route that can return whether the two numbers are amicable or not

Describe the solution you'd like
Adding logic to an '/amicable' route which returns whether the given numbers are amicable or not

### PR DESCRIPTION
**Pull request by honsq90**
Closes #8

### CODE REVIEW

**Comment by ZiyanK** [comment]
Please stick to the consistency of the codebase and refrain from creating new files for these functions. Kindly follow the other routes created as examples.

**Comment by honsq90** [comment]
done!

**Comment by ZiyanK** [comment]
The amicable route has been added. You can still add the tests though! Kindly make those changes and resolve conflicts in tests.js file

**Comment by honsq90** [comment]
Hey @ZiyanK, I noticed that the existing route failed the tests so I've kept my route changes in.

**Pull request closed without merging**
