### PR TITLE
Add a route "/magic" that checks whether a number is a magic number or not #11

### PR DESCRIPTION
**Pull request by pranjalvarshney**
Hi, I've added the functionality which checks and return whether a number is a magic number or not. Added logic to "/magic" route which returns the result.

### CODE REVIEW

**Comment by pranjalvarshney** [comment]
I have resolved the merge conflicts with the base branch.

**Comment by ZiyanK** [comment]
The logic for this route isn't right. A number is said to be a magic number if the sum of its digits is calculated till a single digit recursively by adding the sum of the digits after every addition. If the single-digit comes out to be 1, then the number is a magic number.
For example-
Number= 50113
=> 5+0+1+1+3=10
=> 1+0=1
This is a Magic Number.

Kindly change the logic, add this is a try-catch block, and also send the status code along with the response.

**Comment by pranjalvarshney** [comment]
Ok. I'll make the relevant changes.

**Comment by pranjalvarshney** [comment]
Resolved the merge conflicts with the base branch.

**Comment by ZiyanK** [comment]
Kindly resolve merge conflicts and also indent your code well in accordance with the one in the project.

**Comment by pranjalvarshney** [comment]
resolved conflicts

**Comment by ZiyanK** [comment]
Logic still not correct. This has been worked on by another contributor.

**Pull request closed without merging**
